language: java
jdk:
- oraclejdk8
node_js:
- '7'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- pip install --user codecov
- nvm install 6.6.2
- npm install -g yarn
- yarn install
install:
- cd teams-gui && yarn install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mysql -e "create database IF NOT EXISTS teams_ng; grant all on teams_ng.* to 'root';SET
  GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
addons:
  sonarqube:
    organization: "surfnet" # the key of the org you chose at step #3
    token:
      secure: "kY4WEFO+PcuCqkMwL2QiPw7Om7PIkBM5hUw1w/qA6H1UJEjDtzAuFp7qvc6hrSLTVT7Bj1bVYUXrTEyupZo16KTcIPYY/NW+M7VssjYYOtO8xLnqkhmZ+ssCmPHRGOp5D41IBE40CEKkx9Gu+M3ePVjysIP0QG5zmAuE52tCxb6jhwDxdIp/nkGsjpi4sDGC10vtzEM7/3k7qFAdUX5KKTa7wKl/cBWiqrTASs00EBk7sCcVUt7/2a0V9GZUGDFeZ+NrD8kTT8cFNCDFIpbbTcvfKuzTiO5xfRrpI+BHF+b246/M/fZQREZOkuas1gYRC/8hMiipn+RsGe37ARI1M+0Zmc7b5eYGCCJPVi5PQ7nVpdH9YFGtHHk89nTwe3PY2a4lD6P2azYXzfH7lgtQEV4HoU+TOIHsVcnimNam7maJLA2Xi+fNBEJLh1NEOzry0obGRVSA7GQpfIAhJTHuZwGBQAh4OUmL06P7Nux/TO7biv6cF7Sx+tv3yC+Mv434tkcKF5+M2942mF3v/0uQ0j1inV+91Pt6D0zAeWztHqXTPho4ogMktvWFQwH70XVKyzKjgDqk4Gb4F2p59Fkr8QlT/b/WEon2MnEf0K6mU8bpE0/GfN/ESygYiJMTDk4MUXo4HMoXPHDHisseIFC97qu+kehwFc7+dzuvAVJlTmY="
  mariadb: "10.0"
script:
- mvn test
- cd teams-gui && yarn install && yarn run lint && yarn test
- cd ../ && sonar-scanner
after_success:
- codecov
env:
  global:
    secure: eeO3v8QlhYq9EuJMnZEelJ+RcJF5+2x4tt6fA/qwbOyWSxXVwVyU8ZF5RZDrQlqgClKYwzRXwKq+31k9VCmR/llwkKWvd+mbC1hD4hTLg9NLo5+mc6N+l+KwroviuXUeAXyX34nZrH/EiVliRN47cPSZ4MBA1DO3TsbcE7VfxS52GV4hsIuXK/T0GLrlmtUmr2Hspo8z2t+2AJn48Xw4x94IcPicJ1HRGDjDvN/Hst25fF8ZOgVFnJC4GieUSHYhm0aw9ZkYRBYBDyV7UQsvsxgavVUQGwUVFZT+Xfjuy4d7is1jnLBYjllwDXuUU9cRy9mnsOHbG/RY6NOaiVk1vsr1IXm2Rxnt5cBi2rvLiUYwLstNVL6xZFj6iuCl1FQXlOj4LM15Ua7Ky6mJOi/Fp5w1J3nbvFMSjSF5Md2JIgYV0yQBLVSf1qL/GR/fqVVXgsoIqLYTQpQTi1oIjyAl3VW7I3SgMyTw2xfkB0ucinQxibW5D2xMB6sNgj9MEef+e1benNxQ+tBGVbTWBMQC/Q2Y9DNQda4sRfMGVHQ0dH0CF9RfwGSvvO5GEcCJXEyruwLQ4fJx2r1fqP7yN0/fOhriF3cNSe7V6FmtRS2P17YxCQFBC0ecdFLblyxkzedowKOu9ACiXcDxRfV3a1qSd+d49ANgNRTvbi4rQZEpGRQ=
