language: java
jdk:
  - oraclejdk8
dist: trusty
node_js:
- '10'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- pip install --user codecov
- nvm install v10.13.0
- npm install -g yarn
- yarn install
install:
- cd teams-gui && yarn install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mysql -e "drop database IF EXISTS teams_ng; create database IF NOT EXISTS teams_ng; grant all on teams_ng.* to 'root';SET
  GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
addons:
  mariadb: "10.0"
script:
- mvn test
- cd teams-gui && yarn install && yarn run lint && yarn test
after_success:
- codecov
env:
  global:
    secure: eeO3v8QlhYq9EuJMnZEelJ+RcJF5+2x4tt6fA/qwbOyWSxXVwVyU8ZF5RZDrQlqgClKYwzRXwKq+31k9VCmR/llwkKWvd+mbC1hD4hTLg9NLo5+mc6N+l+KwroviuXUeAXyX34nZrH/EiVliRN47cPSZ4MBA1DO3TsbcE7VfxS52GV4hsIuXK/T0GLrlmtUmr2Hspo8z2t+2AJn48Xw4x94IcPicJ1HRGDjDvN/Hst25fF8ZOgVFnJC4GieUSHYhm0aw9ZkYRBYBDyV7UQsvsxgavVUQGwUVFZT+Xfjuy4d7is1jnLBYjllwDXuUU9cRy9mnsOHbG/RY6NOaiVk1vsr1IXm2Rxnt5cBi2rvLiUYwLstNVL6xZFj6iuCl1FQXlOj4LM15Ua7Ky6mJOi/Fp5w1J3nbvFMSjSF5Md2JIgYV0yQBLVSf1qL/GR/fqVVXgsoIqLYTQpQTi1oIjyAl3VW7I3SgMyTw2xfkB0ucinQxibW5D2xMB6sNgj9MEef+e1benNxQ+tBGVbTWBMQC/Q2Y9DNQda4sRfMGVHQ0dH0CF9RfwGSvvO5GEcCJXEyruwLQ4fJx2r1fqP7yN0/fOhriF3cNSe7V6FmtRS2P17YxCQFBC0ecdFLblyxkzedowKOu9ACiXcDxRfV3a1qSd+d49ANgNRTvbi4rQZEpGRQ=
