# The logging configuration. On a real server this will be a file url. e.g. file://{{ monitoring_tests_dir }}/logback.xml
logging:
  config: classpath:logback.xml
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.hql.internal.ast: ERROR
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.event: TRACE

feature-toggles:
  expiry-date-membership: true

security:
  user:
    name: user
    password: secret

# Is this node in a load-balanced topology responsible for cleaning up resources (See ExpiredInvitationsRemover)
cron:
  node-cron-job-responsible: true
  expression: "0 0/15 * * * ?"

teams:
  default-stem-name: "demo:openconext:org"
  group-name-context: "urn:collab:group:demo.openconext.org:"
  product-name: "OpenConext Teams"
  non-guest-member-of: "urn:collab:org:surf.nl"
  openconext-mails: true

voot:
  serviceUrl: "https://voot.vm.openconext.org"
  accessTokenUri: "https://authz.vm.openconext.org/oauth/token"
  clientId: surf-teams
  clientSecret: secret
  scopes: groups

spring:
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/teams_ng?autoReconnect=true&useSSL=false
    username: root
    password:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  mail:
    host: localhost
    port: 3025
  main:
    banner-mode: "off"

email:
  from: test@surf.nl
  base-url: http://localhost:8001

# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
