# The logging configuration. On a real server this will be a file url. e.g. file://{{ monitoring_tests_dir }}/logback.xml
logging:
  config: classpath:logback.xml
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.event: TRACE

# actual end-point for accessing VOOT
voot:
  service-url: https://voot.vm.openconext.org
  # oauth config for accessing voot.
  access-token-uri: https://authz.vm.openconext.org/oauth/token
  client-id: surf-teams
  client-secret: secret
  scopes: groups

security:
  user:
    name: user
    password: secret

# Is this node in a load-balanced topology responsible for cleaning up resources (See ExpiredInvitationsRemover)
cron:
  node-cron-job-responsible: true

teams:
  default-stem-name: "nl:surfnet:diensten"
  group-name-context: "urn:collab:group:dev.surfteams.nl:"
  white-label: "SURFconext Teams"
  non-guest-member-of: "urn:collab:org:surf.nl"

spring:
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/teams_ng?autoReconnect=true&useSSL=false
    username: root
    password:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  mail:
    host: localhost
    port: 3025
  main:
    banner-mode: "off"

email:
  from: test@surf.nl
  base-url: http://localhost:8080

# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
