# The logging configuration. On a real server this will be a file url. e.g. file://{{ monitoring_tests_dir }}/logback.xml
logging:
  config: classpath:logback.xml
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.hql.internal.ast: ERROR
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.event: TRACE

server:
  error:
    path: "/error"
  server-header:
  servlet:
    session:
      timeout: 28800

feature-toggles:
  expiry-date-membership: false
  person-email-picker: true

secure_cookie: false

api:
  lifecycle:
    username: life
    password: secret

config:
  support-email: help@openconext.nl
  help-link-en: https://wiki.surfnet.nl/pages/viewpage.action?pageId=35422637
  help-link-nl: https://wiki.surfnet.nl/display/conextsupport/SURFconext+teams
  help-link-pt: https://wiki.surfnet.nl/display/conextsupport/SURFconext+teams
  help-tos-en: https://wiki.surfnet.nl/display/conextsupport/Terms+of+Service+%28EN%29
  help-tos-nl: https://wiki.surfnet.nl/display/conextsupport/Terms+of+Service+%28NL%29
  help-tos-pt: https://wiki.surfnet.nl/display/conextsupport/Terms+of+Service+%28NL%29
  main-link: https://www.surfconext.nl
  # Currently supported organizations: SURFconext, OpenConext and RCTSaai
  organization: OpenConext
  sponsor: SURF
  supported_language_codes: en,nl

security:
  user:
    name: user
    password: secret

# Is this node in a load-balanced topology responsible for cleaning up resources (See Scheduler)
cron:
  node-cron-job-responsible: true
  expression: "0 0/15 * * * ?"

teams:
  default-stem-name: "demo:openconext:org"
  group-name-context: "urn:collab:group:demo.openconext.org:"
  product-name: "OpenConext"
  non-guest-member-of: "urn:collab:org:surf.nl"

sp_dashboard:
  user-name: spdashboard
  password: secret
  person-urn: "urn:collab:person:surfnet.nl:sp-dashboard-C133A36F-CFCA-4F3D-87CE-7ECE29773FE0"
  name: "SP Dashboard"
  email: "support@surfconext.nl"


super-admins-team:
  urns:
    - "demo:openconext:org:super_admins"
    - "demo:openconext:org:another_super_admins"
#    - "demo:openconext:org:riders"

voot:
  serviceUrl: "https://voot.vm.openconext.org"
  accessTokenUri: "https://authz.vm.openconext.org/oauth/token"
  clientId: surf-teams
  clientSecret: secret
  scopes: groups

spring:
  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      initialize-schema: always
      cleanup-cron: "0 * * * * *"
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/teams_ng?autoReconnect=true&useSSL=false&useMysqlMetadata=true
    username: root
    password:
  mail:
    host: localhost
    port: 3025
  main:
    banner-mode: "off"
  flyway:
    validate-on-migrate: false
    table: schema_version
  security:
    user:
      name: na
      password: na

email:
  from: test@surf.nl
  base-url: http://localhost:3006

# We disable all endpoints except health for the load-balancer and info for git information.
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
