ALTER TABLE invitation_message CONVERT TO CHARACTER SET utf8;
ALTER TABLE invitations CONVERT TO CHARACTER SET utf8;
ALTER TABLE requests CONVERT TO CHARACTER SET utf8;

ALTER TABLE invitations ENGINE = InnoDB;
ALTER TABLE requests ENGINE = InnoDB;

